config/routes.rb
Rails.application.routes.draw do
  root to: 'donors#index'

  resources :donors
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController

  def index
    @donors = Donor.all
  end

  def new
    @donor = Donor.new
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def create
    @donor = Donor.new(donor_params)
    if @donor.save
      flash[:notice] = "Donor information saved"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      render 'new'
    end
  end

  def show
    @donor = Donor.find(params[:id])
  end

  def edit
    @donor = Donor.find(params[:id])
  end

  def update
    @donor = Donor.find(params[:id])
    if @donor.update(donor_params)
      flash[:notice] = "Donor information updated"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      render 'edit'
    end
  end

  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy
    flash[:notice] = "Account has been deleted"
    redirect_to root_path
  end

private
  def donor_params
    params.require(:donor).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/donors/_donor.html.erb
<li><%= link_to "#{donor.first_name} #{donor.last_name}", donor_path(donor) %></li>

app/views/donors/_form.html.erb
<%= render 'layouts/errors', object: @donor %>

<%= form_for @donor, remote: true do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.submit %>
<% end %>

app/views/donors/create.js.erb
$('#new-donor').hide();
$('.donors-list').append("<%= j render @donor %>");

app/views/donors/edit.html.erb
<h1>Edit Donor</h1>

<%= render 'form' %>

app/views/donors/edit.js.erb
$('#edit-donor').append("<%= j render 'form' %>");

app/views/donors/index.html.erb
<h1>Donors</h1>

<ul class='donors-list'>
  <%= render @donors %>
</ul>

<div id="new-donor"></div>

app/views/donors/new.html.erb
<h1>New Donor</h1>

<%= render 'form' %>

app/views/donors/new.js.erb
$('#new-donor').append("<%= j render 'form' %>");

app/views/donors/show.html.erb
<h1 id='donor-title'><%= @donor.first_name %> <%= @donor.last_name %></h1>

<%= link_to "Edit", edit_donor_path(@donor), remote: true %>

<%= link_to "Delete", donor_path(@donor), data: {
          confirm: "Are you sure that you want to delete this account?",
          method: 'delete'
} %>

<div id="edit-donor"></div>

app/views/donors/update.js.erb
$('#edit-donor').hide();
$('#donor-title').text("<%= @donor.first_name %> <%= @donor.last_name %>");

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nonprofit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class= "navbar">
    <h3>Non-profit Tracker</h3>
    <ul>
      <li><%= link_to "List of Donors", root_path %></li>
      <li><%= link_to "New Donor", new_donor_path, remote: true  %></li>
    </ul>
</div>

<%= flash[:notice] %>
<%= yield %>

</body>
</html>